import java.util.List;
import com.sbnz.bankcredit.model.Contract;
/*
rule "go1"
when
    $list: List() from accumulate(
    	$c: Contract(), collectList()
    )
    isContainedIn($num, $list; )
then
    System.out.println( "office is in the house" );
end

query isContainedIn( int $num, List list )
  $num := Number(intValue == list.size()) from accumulate (
        	$f : Contract(),
        	count($f)
        )
end
*/