package rules;

import com.sbnz.bankcredit.model.Client;
import com.sbnz.bankcredit.model.Contract;
import com.sbnz.bankcredit.model.CreditType;
import com.sbnz.bankcredit.model.CreditRequest;
import java.util.Date;
import java.util.List;
import com.sbnz.bankcredit.dto.ConditionDTO;
import com.sbnz.bankcredit.dto.ContractDTO;

function int greaterThan(int numb, int cond) {
	if (numb > cond) {
		return 1;
	}
	else{
		return 0;
	}
}

function int checkPrice(double totalPrice, double loanValue, double valueForComp) {
	if (totalPrice >= valueForComp*loanValue) {
		return 1;
	}
	else{
		return 0;
	}	
}

function int returnOppositeValue(int number) {
	if (number == 0) {
		return 1;
	}
	else {
		return 0;
	}
}

rule 'Osnovna kamatna stopa 8%'
	salience 10
	agenda-group "reward points"
	no-loop
	when
		$contract : Contract($id : id, signed == false)	
		not(ContractDTO())
		$creditRequest : CreditRequest((sumOfMoney < 10000 && monthlyPaymentPeriod >= 60) 	
		|| (sumOfMoney >= 10000 && sumOfMoney < 30000 && monthlyPaymentPeriod >= 96)
		|| (sumOfMoney >= 30000 && sumOfMoney < 60000 && monthlyPaymentPeriod >= 120) 
		|| (sumOfMoney >= 60000 && sumOfMoney < 100000 && monthlyPaymentPeriod >= 180)) 
	then
		insert (new ContractDTO($id, 8, 0)); 
		System.out.println("Osnovna kamatna stopa 8%");
	end

rule 'Osnovna kamatna stopa 6%'
	salience 10
	agenda-group "reward points"
	no-loop
	when
		$contract : Contract($id : id, signed == false)	
		not(ContractDTO())
		$creditRequest : CreditRequest((sumOfMoney < 10000 && monthlyPaymentPeriod >= 36 && monthlyPaymentPeriod < 60) 
		|| (sumOfMoney >= 10000 && sumOfMoney < 30000 && monthlyPaymentPeriod >= 60 && monthlyPaymentPeriod < 96)
		|| (sumOfMoney >= 30000 && sumOfMoney < 60000 && monthlyPaymentPeriod >= 96 && monthlyPaymentPeriod < 120) 
		|| (sumOfMoney >= 60000 && sumOfMoney < 100000 && monthlyPaymentPeriod >= 120 && monthlyPaymentPeriod < 180)
		|| (sumOfMoney >= 100000 && monthlyPaymentPeriod >= 180)) 
	then
		insert (new ContractDTO($id, 6, 0)); 
		System.out.println("Osnovna kamatna stopa 6%");
	end
		
rule 'Osnovna kamatna stopa 4%'
	salience 10
	agenda-group "reward points"
	no-loop
	when
		$contract : Contract($id : id, signed == false)	
		not(ContractDTO())
		$creditRequest : CreditRequest((sumOfMoney < 10000 && monthlyPaymentPeriod < 36) 
		|| (sumOfMoney >= 10000 && sumOfMoney < 30000 && monthlyPaymentPeriod < 60)
		|| (sumOfMoney >= 30000 && sumOfMoney < 60000 && monthlyPaymentPeriod < 96) 
		|| (sumOfMoney >= 60000 && sumOfMoney < 100000 && monthlyPaymentPeriod < 120)
		|| (sumOfMoney >= 100000 && monthlyPaymentPeriod < 180)) 
	then
		insert (new ContractDTO($id, 4, 0)); 
		System.out.println("Osnovna kamatna stopa 4%");
	end
	
rule "5 bodova"
	agenda-group "reward points"
	salience 10
	//lock-on-active
	no-loop
	when
		$client : Client()
		ContractDTO(rewardPoints == 0)
		$invHous : Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, creditType == CreditType.Housing || creditType == CreditType.Investment),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$sumOfMoney :  Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, sumOfMoney > 100000),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$account : Number (intValue >=0) from accumulate(
				Client( this == $client, System.currentTimeMillis() - accountOpeningDate.getTime() >= 1000*60*60*24*365*4),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		
		$contracts : Number(intValue >=0) from accumulate(
				$c : Contract(active == false, signed == true, client == $client),
				count($c)
		)
		$activeContracts: Number(intValue >=0) from accumulate(
				Contract(active == true, signed == true, client == $client),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		
		$creditRequest : CreditRequest()
		
		$allContracts : List() from collect(Contract(active == false, signed == true))
		
		$guarantor: Number(intValue >=0) from accumulate(
				$c :  Contract(active == false, signed == true, client == $creditRequest.getWarrantly().getGuarantor()) from $allContracts,
				count($c)
		)
		$realEstatesTotalValue: Number(doubleValue >=0) from accumulate
				(
				CreditRequest(client == $client, warrantly != null, warrantly.realEstate != null, $realEstates : warrantly.realEstate),
				init(double count = 0; ),
				action(
				for (Object re : $realEstates) {
					count = count + ((RealEstate) re).getPrice();
				}),
				result (count)
		)
	then
		int totalConditions = 7;
		int totalPoints = 5 + $contracts.intValue() + $guarantor.intValue();
		int completedConditions = $invHous.intValue() + $sumOfMoney.intValue() + $account.intValue() + greaterThan($contracts.intValue(), 1) +
		$activeContracts.intValue() + greaterThan($guarantor.intValue(), 0) + checkPrice($realEstatesTotalValue.intValue(), $creditRequest.getSumOfMoney(), 2);
		if (completedConditions >= 2){
			insert(new ConditionDTO(totalPoints, totalConditions, completedConditions));
		}
		System.out.println("5 bodova");
	end

rule "4 boda"
	agenda-group "reward points"
	salience 10
	no-loop
	when
		$client : Client()
		ContractDTO(rewardPoints == 0)
		$invHous : Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, creditType == CreditType.Housing || creditType == CreditType.Investment),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$sumOfMoney :  Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, sumOfMoney > 50000),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		
		$contracts : Number(intValue >=0) from accumulate(
				$c : Contract(active == false, signed == true, client == $client),
				count($c)
		)
		
		$account : Number (intValue >=0) from accumulate(
			Client( this == $client, System.currentTimeMillis() - accountOpeningDate.getTime() >= 1000*60*60*24*365*2),
			init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		
		$creditRequest : CreditRequest()
		
		$allContracts : List() from collect(Contract(active == false, signed == true))
		
		$realEstatesTotalValue: Number(doubleValue >=0) from accumulate(
		CreditRequest(client == $client, warrantly != null, warrantly.realEstate != null, $realEstates : warrantly.realEstate),
		init(double count = 0; ),
				action(
				for (Object re : $realEstates) {
					count = count + ((RealEstate) re).getPrice();
				}),
				result (count)
		)
	then
		int totalConditions = 5;
		int totalPoints = 4 + $contracts.intValue();
		int completedConditions = $invHous.intValue() + $sumOfMoney.intValue() + $account.intValue() + greaterThan($contracts.intValue(), 0) + checkPrice($realEstatesTotalValue.intValue(), $creditRequest.getSumOfMoney(), 1.5) ;
		if (completedConditions >= 2){
			insert(new ConditionDTO(totalPoints, totalConditions, completedConditions));
		}
		System.out.println("4 bodova");
	end	

rule "3 boda"
	agenda-group "reward points"
	salience 10
	no-loop
	when
		$client : Client()
		ContractDTO(rewardPoints == 0)
		$consCredit : Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, creditType == CreditType.Consumer),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		) 
		$sumOfMoney :  Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, sumOfMoney > 15000),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$account : Number (intValue >=0) from accumulate(
				Client( this == $client, System.currentTimeMillis() - accountOpeningDate.getTime() >= 1000*60*60*24*365),
				init(int count = 0; ),
					action(count = 1;),
					result (count)
		)
		
		$activeContracts: Number(intValue >=0) from accumulate(
				Contract(active == true, signed == true, client == $client),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		
		$guarantor: Number(intValue >=0) from accumulate(
				$cr :  CreditRequest(client == $client, warrantly != null, warrantly.guarantor != null),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		
		
	then
		int totalConditions = 5;
		int totalPoints = 3;
		int completedConditions = $consCredit.intValue() + $sumOfMoney.intValue() + $account.intValue() + returnOppositeValue($activeContracts.intValue()) + $guarantor.intValue() ;
		if (completedConditions >= 2){
			insert(new ConditionDTO(totalPoints, totalConditions, completedConditions));
		}
		System.out.println("3 boda " + $activeContracts.intValue());
	end	

rule "2 boda"
	agenda-group "reward points"
	salience 10
	no-loop
	when
		$client : Client()
		ContractDTO(rewardPoints == 0)
		$invHous : Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, creditType == CreditType.Housing || creditType == CreditType.Investment),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		) 
		$sumOfMoney :  Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, sumOfMoney > 35000),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$account : Number (intValue >=0) from accumulate(
				Client( this == $client, System.currentTimeMillis() - accountOpeningDate.getTime() >= 1000*60*60*24*365),
				init(int count = 0; ),
					action(count = 1;),
					result (count)
		)
	then
		int totalConditions = 3;
		int totalPoints = 2;
		int completedConditions = $invHous.intValue() + $sumOfMoney.intValue() + $account.intValue();
		if (completedConditions >= 2){
			insert(new ConditionDTO(totalPoints, totalConditions, completedConditions));
		}
		System.out.println("2 boda ");
	end

rule "1 bod"
	agenda-group "reward points"
	salience 10
	no-loop
	when
		$client : Client()
		ContractDTO(rewardPoints == 0)
		$sumOfMoney :  Number (intValue >= 0) from accumulate(
				CreditRequest(client == $client, sumOfMoney > 10000),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$activeContracts: Number(intValue >=0) from accumulate(
				Contract(active == true, signed == true, client == $client),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
		$guarantorRe: Number(intValue >=0) from accumulate(
				$cr :  CreditRequest(client == $client, warrantly != null, warrantly.insurance == false),
				init(int count = 0; ),
				action(count = 1;),
				result (count)
		)
	then
		int totalConditions = 3;
		int totalPoints = 1;
		int completedConditions = returnOppositeValue($activeContracts.intValue()) + $sumOfMoney.intValue() + $guarantorRe.intValue();
		if (completedConditions >= 2){
			insert(new ConditionDTO(totalPoints, totalConditions, completedConditions));
		}
		System.out.println("1 bod ");
	end		
	

rule "Dodaj dodatne bodove"
	agenda-group "reward points"
	salience 5
	no-loop
	when
		$contract : ContractDTO(rewardPoints == 0)
		$client : Client()
		$total :  Number (intValue > 0) from accumulate(
				ConditionDTO($totalPoints : totalPoints, $percent : percent),
				init(int count = 0; double perc = 0; boolean greaterThan50 = false),
				action(
					if (greaterThan50 == false && $percent > perc && $percent < 50){
						perc = $percent; count = $totalPoints;
					}
					else if ($percent >= 50) {
						greaterThan50 = true;
						if ($totalPoints > count) {
							count = $totalPoints;
						}
					}
					else if (greaterThan50 == true) {
						if ($totalPoints > count) {
							count = $totalPoints;
						}
					}
				),
				result (count)
		)
	then
		System.out.println("rp " + $client.getRewardPoints() + " total " + $total.intValue());
		int val = $client.getRewardPoints() + $total.intValue();
		modify($client) {setRewardPoints(val);}
		modify($contract) {setRewardPoints(val);}
		System.out.println("Dodaj dodatne bodove");
	end

rule "Kamata se umanjuje za 5% i racuna se mjesecna rata"
	agenda-group "reward points"
	salience 5
	no-loop
	when
		$contractDTO : ContractDTO(rewardPoints >= 2, rewardPoints < 10, $basicInterest : basicInterest)
		$client : Client()
		$contract : Contract (client == $client, signed == false, active == true, interest == 0.0)
		$creditRequest : CreditRequest($sumOfMoney : sumOfMoney, $monthlyPaymentPeriod : monthlyPaymentPeriod) 
	then
		double interest = $basicInterest*0.95;
		double totalSum =  $sumOfMoney + interest/100*$sumOfMoney;
		double paymentMonthly = totalSum/(double) $monthlyPaymentPeriod;
		modify($contract) {setInterest(interest);}
		modify($contract) {setMonthlyPayment(paymentMonthly);}
		modify($contract) {setRemainingSum(totalSum);}
		modify($client) {setRewardPoints($client.getRewardPoints() - 1);}
		System.out.println("5% " + $contract.getInterest());
		
	end

rule "Kamata se umanjuje za 20% i racuna se mjesecna rata"
	agenda-group "reward points"
	salience 5
	no-loop
	when
		$contractDTO : ContractDTO(rewardPoints >= 10, rewardPoints < 15, $basicInterest : basicInterest)
		$client : Client()
		$contract : Contract (client == $client, signed == false, active == true, interest == 0.0)
		$creditRequest : CreditRequest($sumOfMoney : sumOfMoney, $monthlyPaymentPeriod : monthlyPaymentPeriod) 
	then
		double interest = $basicInterest*0.80;
		double totalSum =  $sumOfMoney + interest/100*$sumOfMoney;
		double paymentMonthly = totalSum/(double) $monthlyPaymentPeriod;
		modify($contract) {setInterest(interest);}
		modify($contract) {setMonthlyPayment(paymentMonthly);}
		modify($contract) {setRemainingSum(totalSum);}
		modify($client) {setRewardPoints($client.getRewardPoints() - 1);}
		System.out.println("20% " + $contract.getInterest());
	end

rule "Kamata se umanjuje za 30% i racuna se mjesecna rata"
	agenda-group "reward points"
	salience 5
	no-loop
	when
		$contractDTO : ContractDTO(rewardPoints >= 15, rewardPoints < 20, $basicInterest : basicInterest)
		$client : Client()
		$contract : Contract (client == $client, signed == false, active == true, interest == 0.0)
		$creditRequest : CreditRequest($sumOfMoney : sumOfMoney, $monthlyPaymentPeriod : monthlyPaymentPeriod) 
	then
		double interest = $basicInterest*0.70;
		double totalSum =  $sumOfMoney + interest/100*$sumOfMoney;
		double paymentMonthly = totalSum/(double) $monthlyPaymentPeriod;
		modify($contract) {setInterest(interest);}
		modify($contract) {setMonthlyPayment(paymentMonthly);}
		modify($contract) {setRemainingSum(totalSum);}
		modify($client) {setRewardPoints($client.getRewardPoints() - 2);}
		System.out.println("30% " + $contract.getInterest());
	end	

rule "Kamata se umanjuje za 40% i racuna se mjesecna rata"
	agenda-group "reward points"
	salience 5
	no-loop
	when
		$contractDTO : ContractDTO(rewardPoints >= 20, $basicInterest : basicInterest, $rp : rewardPoints)
		$client : Client()
		$contract : Contract (client == $client, signed == false, active == true, interest == 0.0)
		$creditRequest : CreditRequest($sumOfMoney : sumOfMoney, $monthlyPaymentPeriod : monthlyPaymentPeriod) 
	then
		double interest = $basicInterest*0.60;
		double totalSum =  $sumOfMoney + interest/100*$sumOfMoney;
		double paymentMonthly = totalSum/(double) $monthlyPaymentPeriod;
		modify($contract) {setInterest(interest);}
		modify($contract) {setMonthlyPayment(paymentMonthly);}
		modify($contract) {setRemainingSum(totalSum);}
		modify($client) {setRewardPoints($client.getRewardPoints() - 5);}
		System.out.println("40% " + $contract.getInterest());
	end

